apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebmvc
spec:
  selector:
    matchLabels:
      app: mywebmvc
  replicas: 3
  template: # template for the pods
    metadata:
      labels:
        app: mywebmvc
    spec:
      containers:
      - name: mywebmvccont
        image: ajitjog/coremvcapp:v1

